### ISSUE TITLE
NameError: global name 'urllib' is not defined defined

### ISSUE THREAD

**Issue by mtravis** [Geolicious/geotweet#7]
Reinstalled after issue #6 sorted. Now get this error.  

```
Traceback (most recent call last):
File "C:/PROGRA~1/QGISWI~1/apps/qgis/./python\qgis\utils.py", line 219, in startPlugin
plugins[packageName] = package.classFactory(iface)
File "C:/Users/yakus/.qgis2/python/plugins\geotweet-master\__init__.py", line 35, in    classFactory
return geotweet(iface)
File "C:/Users/yakus/.qgis2/python/plugins\geotweet-master\geotweet.py", line 75, in __init__
self.dlg = geotweetDialog()
File "C:/Users/yakus/.qgis2/python/plugins\geotweet-master\geotweet_dialog.py", line 53, in __init__
urllib.urlretrieve('https://github.com/tweepy/tweepy/archive/master.zip', tempfolder + os.sep + 'master.zip')
NameError: global name 'urllib' is not defined defined
```

**Comment by riccardoklinger** [comment]
solved the issue in recent master. @mtravis please try to run 
`import tweepy` in your python console in qgis.
if you have installed tweepy "correctly" you shouldn't see this issue!
