### ISSUE TITLE
saving raw tweet list to file doesn't work on win

### ISSUE THREAD

**Issue by riccardoklinger** [Geolicious/geotweet#8]
on windows I get the message: Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\OSGEO4~1\apps\Python27\lib\codecs.py", line 881, in open
    file = **builtin**.open(filename, mode, buffering)
IOError: [Errno 22] invalid mode ('wb') or filename: 'c:\users\rikl\appdata\local\tempTweets_2015-05-18 10:47:42.txt'

on linux it is working fine

**Comment by riccardoklinger** [comment]
the filename should not contain any ":"
