### ISSUE TITLE
unknown error when reading lot's of tweets

### ISSUE THREAD

**Issue by riccardoklinger** [Geolicious/geotweet#9]
I tried to read 100.000 tweets from twitter and received this error after a while:

Traceback (most recent call last):
  File "/home/ricckli/.qgis2/python/plugins/geotweet/geotweet.py", line 324, in run
    stream.filter(locations=[-180,-90,180,90])
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 428, in filter
    self._start(async)
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 346, in _start
    self._run()
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 255, in _run
    self._read_loop(resp)
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 307, in _read_loop
    next_status_obj = buf.read_len(length)
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 161, in read_len
    self._buffer += self._stream.read(read_len).decode("ascii")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1788: ordinal not in range(128)

**Comment by ugurh** [comment]
Can you fix it ? ı have same errors
